### ISSUE TITLE
Missing gmpxx.h, Need Enable C++ Detection & Support

### ISSUE THREAD

**Issue by wbraswell** [rsimoes/Alien-GMP#4]
System installs include gmpxx.h:

https://packages.ubuntu.com/artful/i386/libgmp-dev/filelist

RPerl, which is now about to list Alien::GMP as a dependency, needs the missing gmpxx.h file.

According to the official docs, we can fix this with a configure switch:

https://gmplib.org/manual/Build-Options.html

    --enable-cxx=detect

**Comment by plicease** [comment]
I've added optional C++ bindings support with the 1.06_01 release.  You will be able to use the alt 'gmpxx' to get the correct cflags / libs:

https://metacpan.org/pod/release/PLICEASE/Alien-GMP-1.06_01/lib/Alien/GMP.pm#C++-support

I will make a production release when it looks ready.

**Comment by plicease** [comment]
1.07 is now on CPAN.
